#!/bin/bash
set -euo pipefail
HERE="$(dirname "$(readlink -f "$0")")"

CONTEXT=$HERE/../base source "$HERE"/../lib.sh
CONTEXT=$HERE source "$HERE"/../lib.sh
docker run -it -v $HOME:/home/coder -v $TOP:/opt/code "$IMAGE" tmux -2
