#!/bin/bash
HERE="$(dirname "$(readlink -f "$0")")"
source "$HERE"/../lib.sh

"$HERE"/../base/run
docker-build "$HERE"

# this closely emulates our production docker-run arguments
docker run \
    -P \
    --read-only \
    "$IMAGE" \
    "$@"
